# MNIST training configuration

model:
  l1_chan: 4
  l2_chan: 8
  l3_chan: 16
  fc1_out: 30
  optimizer: sgd
  optimizer_params:
    lr: 0.1
    momentum: 0.8
    nesterov: true

trainer:
  check_val_every_n_epoch: 1
  max_epochs: 5

data:
  batch_size: 64
  data_dir: ./data/MNIST
  num_workers: 11
